# Generated by Django 4.1.3 on 2022-12-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=400)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
    ]
