# Generated by Django 4.1.3 on 2022-12-14 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='address',
            new_name='stud_address',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='email',
            new_name='stud_email',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='stud_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='phno',
            new_name='stud_phno',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='place',
            new_name='stud_place',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AddField(
            model_name='students',
            name='stud_id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
